### ISSUE TITLE
模型初始化有问题

### ISSUE THREAD

**Issue by zmingshi** [ghosthamlet/gpt2-ml-torch#10]
您好，我下载了 网盘的模型，也验证了文件完整性没有问题，运行demo 的时候出问题，提示有参数没有初始化。这个是不是有问题？ 自己convert 的模型也有同样的问题～

`python gpt2_ml_torch/generate.py --prompt "【上联】悠悠柳岸落红霞 【下联】" --max_len 100 --n_seq 3 --model_path ./models/mega-clue-tok/`

`Some weights of GPT2LMHeadModel were not initialized from the model checkpoint at ./models/mega-clue-tok/ and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence`

0. 【上联】悠悠柳岸落红霞 【下联】 落 落 柳 荫 映 水 波 【 横 批 】 好 客 风 景 常 相 顾 【 注 音 】 悠 柳 落 红 霞 清 晨 雾 起 漫 阳 光 【 对 】 ， 好 客 风 景 常 相 逢 晨 雾 漫 漫 映 好 景 柳 絮 随 风 落 柳 枝 ， 好 客 风 光 喜 迎 人 晨 雾 漫 漫 映 好 景 天 边 柳 絮 随 风

1. 【上联】悠悠柳岸落红霞 【下联】 千 金 飞 花 梦 相 忆 【 横 批 】 君 不 见 柳 眠 落 花 花 梦 见 ， 风 雨 更 深 秋 色 深 。 柳 岸 花 魂 醉 东 风 柳 岸 花 梦 秋 风 柳 梢 花 影 梦 相 忆 柳 栖 花 柳 梦 春 风 柳 岸 花 柳 梦 春 风 秋 风 柳 岸 花 花 梦 相 思 柳 下 有 莺 花

2. 【上联】悠悠柳岸落红霞 【下联】 桃 枝 袅 袅 桃 花 风 【 横 批 】 艳 春 风 作 为 一 名 资 深 的 中 餐 研 发 人 员 ， 每 年 春 天 ， 就 是 一 个 小 传 奇 的 开 启 ， 有 些 人 会 在 春 天 被 推 上 首 席 ， 有 些 人 则 会 黯 然 离 开 。 桃 花 开 了 ， 桃 花 下 的 人 却 凋 零 ， 这 么 美 丽

**Comment by ghosthamlet** [comment]
提示中的['lm_head.weight']这个是输出层的权重，输出层和嵌入层是共享绑定权重的，没有独立权重，所以加载权重时会有这个提示，没有影响，你生成的内容效果也是正常的，不过这个模型没有专门微调诗词生成，生成普通文章的质量会更好。
另外如果模型内有任何一层初始化失败，生成的内容会是乱码或者质量非常差。

**Comment by zmingshi** [comment]
> 提示中的['lm_head.weight']这个是输出层的权重，输出层和嵌入层是共享绑定权重的，没有独立权重，所以加载权重时会有这个提示，没有影响，你生成的内容效果也是正常的，不过这个模型没有专门微调诗词生成，生成普通文章的质量会更好。
> 另外如果模型内有任何一层初始化失败，生成的内容会是乱码或者质量非常差。
@ghosthamlet 
非常感谢回复！🙏 我想做一些文本生成的任务finetune，对transformers 那个库不太熟悉，方便的话，可以给一个具体的例子的link 吗？感激不尽～ 看你之前的答复可以使用deepspeed 多卡finetune，我这边想尝试下，还不知道finetune 代码怎么写～

**Comment by ghosthamlet** [comment]
@zmingshi 微调的话最好能尽量先熟悉transformers类库，这样微调过程遇到的问题能比较容易的处理，我在https://github.com/ghosthamlet/gpt2-ml-torch/issues/8#issuecomment-739487726 这个问题回答中有Transformers对应版本的文档和实例链接，做文本生成的任务只需要看实例页面的language-modeling实例即可，如果微调过程有什么问题可以继续问我。

用deepspeed训练基本上不需要修改之前微调的代码，只需要做一些配置和增加几行代码，但训练过程可能遇到各种问题，也应该先熟悉https://github.com/microsoft/DeepSpeed 文档，他的文挡不多，全部读完对训练大有好处，有问题可以继续在这里发出来。

### 更新：
我看到有三个朋友都在问微调的问题，我还是写一个完整的实例吧，这样大家可以参照一下。

### DeepSpeed微调示例更新：
https://github.com/ghosthamlet/gpt2-ml-torch/blob/master/finetune_lm.py

**Comment by zmingshi** [comment]
> @zmingshi 微调的话最好能尽量先熟悉transformers类库，这样微调过程遇到的问题能比较容易的处理，我在[#8 (comment)](https://github.com/ghosthamlet/gpt2-ml-torch/issues/8#issuecomment-739487726) 这个问题回答中有Transformers对应版本的文档和实例链接，做文本生成的任务只需要看实例页面的language-modeling实例即可，如果微调过程有什么问题可以继续问我。
> 
> 用deepspeed训练基本上不需要修改之前微调的代码，只需要做一些配置和增加几行代码，但训练过程可能遇到各种问题，也应该先熟悉https://github.com/microsoft/DeepSpeed 文档，他的文挡不多，全部读完对训练大有好处，有问题可以继续在这里发出来。
> 
> ### 更新：
> 我看到有三个朋友都在问微调的问题，我还是写一个完整的实例吧，这样大家可以参照一下。
> 
> ### DeepSpeed微调示例更新：
> https://github.com/ghosthamlet/gpt2-ml-torch/blob/master/finetune_lm.py
多谢回复，有问题再向你请教！！～

**Comment by ghosthamlet** [comment]
不客气，有微调的问题可以再开一个issue

**Comment by zhenhao-huang** [comment]
> 不客气，有微调的问题可以再开一个issue

博主，微调的话单卡、多卡分别需要多大显存
