### ISSUE TITLE
微调需要多大的显存

### ISSUE THREAD

**Issue by zhenhao-huang** [ghosthamlet/gpt2-ml-torch#11]
你好，微调模型单卡，多卡需要多大的显存？

**Comment by ghosthamlet** [comment]
@zhenhao-huang
用deepspeed的cpu offload训练，token长度300，batch大小为1的时候，单卡1080TI的11GB就够用了，多卡的话如果只做数据并行，显存需求一样，如果加上deepspeed的pipeline，可以继续减少显存需求，但pipeline的方法我还在试验。

**Comment by zhenhao-huang** [comment]
> @zhenhao-huang
> 用deepspeed的cpu offload训练，token长度300，batch大小为1的时候，单卡1080TI的11GB就够用了，多卡的话如果只做数据并行，显存需求一样，如果加上deepspeed的pipeline，可以继续减少显存需求，但pipeline的方法我还在试验。

谢谢。我看微调代码使用是deepspeed --num_nodes 1 --num_gpus 1 finetune.py --log_name finetune_large_stage1 --seq_len 300 --epochs 3 --batch_size 1 --lr 5e-8 --device_ids 0 --train_data datasets/test_train.txt --valid_data datasets/test_val.txt --pretrained_path models/mega-clue-tok --freeze_body，
finetune.py 这个文件在哪

**Comment by zhenhao-huang** [comment]
> @zhenhao-huang
> 用deepspeed的cpu offload训练，token长度300，batch大小为1的时候，单卡1080TI的11GB就够用了，多卡的话如果只做数据并行，显存需求一样，如果加上deepspeed的pipeline，可以继续减少显存需求，但pipeline的方法我还在试验。

谢谢。我的一张显卡大小是8g，如果把单卡1个batch需要的显存大小11g分到两个显卡上，相当于16g显卡，这是否可行？
我使用了微调代码中双卡情况，但跑的时候只占用一张卡。

**Comment by ghosthamlet** [comment]
@zhenhao-huang 这需要用到deepspeed的pipeline，目前还不支持，我有初步的试验代码，但还没有完全测试通过。不过你可以把token长度尽量减小，8G也可以够用。

**Comment by zhenhao-huang** [comment]
减小token会影响结果吗

**Comment by ghosthamlet** [comment]
收敛可能会稍微慢些，一次生成的文本长度会相应减小，文本的上下文范围也会减小，上下文范围内的文本质量一般不会有影响。
