### ISSUE TITLE
权重有缺失

### ISSUE THREAD

**Issue by Jasonjk3** [ghosthamlet/gpt2-ml-torch#12]
你好，请问下我检查过文件完整性SHA256是一致的，但是运行时有提示权重缺失
windows10环境下

Some weights of the model checkpoint at models/mega-clue-tok/ were not used when initializing GPT2LMHeadModel: ['emb_norm.weight', 'emb_norm.bias', 'h.32.ln_1.weight', 'h.32.ln_1.bias', 'h.32.attn.bias', 'h.32.attn.masked_bias', 'h.32.attn.c_attn.weight', 'h.32.attn.c_attn.bias', 'h.32.attn.c_proj.weight', 'h.32.attn.c_proj.bias', 'h.32.ln_2.weight', 'h.32.ln_2.bias', 'h.32.mlp.c_fc.weight', 'h.32.mlp.c_fc.bias', 'h.32.mlp.c_proj.weight', 'h.32.mlp.c_proj.bias', 'h.33.ln_1.weight', 'h.33.ln_1.bias', 'h.33.attn.bias', 'h.33.attn.masked_bias', 'h.33.attn.c_attn.weight', 'h.33.attn.c_attn.bias', 'h.33.attn.c_proj.weight', 'h.33.attn.c_proj.bias', 'h.33.ln_2.weight', 'h.33.ln_2.bias', 'h.33.mlp.c_fc.weight', 'h.33.mlp.c_fc.bias', 'h.33.mlp.c_proj.weight', 'h.33.mlp.c_proj.bias', 'h.34.ln_1.weight', 'h.34.ln_1.bias', 'h.34.attn.bias', 'h.34.attn.masked_bias', 'h.34.attn.c_attn.weight', 'h.34.attn.c_attn.bias', 'h.34.attn.c_proj.weight', 'h.34.attn.c_proj.bias', 'h.34.ln_2.weight', 'h.34.ln_2.bias', 'h.34.mlp.c_fc.weight', 'h.34.mlp.c_fc.bias', 'h.34.mlp.c_proj.weight', 'h.34.mlp.c_proj.bias', 'h.35.ln_1.weight', 'h.35.ln_1.bias', 'h.35.attn.bias', 'h.35.attn.masked_bias', 'h.35.attn.c_attn.weight', 'h.35.attn.c_attn.bias', 'h.35.attn.c_proj.weight', 'h.35.attn.c_proj.bias', 'h.35.ln_2.weight', 'h.35.ln_2.bias', 'h.35.mlp.c_fc.weight', 'h.35.mlp.c_fc.bias', 'h.35.mlp.c_proj.weight', 'h.35.mlp.c_proj.bias', 'h.36.ln_1.weight', 'h.36.ln_1.bias', 'h.36.attn.bias', 'h.36.attn.masked_bias', 'h.36.attn.c_attn.weight', 'h.36.attn.c_attn.bias', 'h.36.attn.c_proj.weight', 'h.36.attn.c_proj.bias', 'h.36.ln_2.weight', 'h.36.ln_2.bias', 'h.36.mlp.c_fc.weight', 'h.36.mlp.c_fc.bias', 'h.36.mlp.c_proj.weight', 'h.36.mlp.c_proj.bias', 'h.37.ln_1.weight', 'h.37.ln_1.bias', 'h.37.attn.bias', 'h.37.attn.masked_bias', 'h.37.attn.c_attn.weight', 'h.37.attn.c_attn.bias', 'h.37.attn.c_proj.weight', 'h.37.attn.c_proj.bias', 'h.37.ln_2.weight', 'h.37.ln_2.bias', 'h.37.mlp.c_fc.weight', 'h.37.mlp.c_fc.bias', 'h.37.mlp.c_proj.weight', 'h.37.mlp.c_proj.bias', 'h.38.ln_1.weight', 'h.38.ln_1.bias', 'h.38.attn.bias', 'h.38.attn.masked_bias', 'h.38.attn.c_attn.weight', 'h.38.attn.c_attn.bias', 'h.38.attn.c_proj.weight', 'h.38.attn.c_proj.bias', 'h.38.ln_2.weight', 'h.38.ln_2.bias', 'h.38.mlp.c_fc.weight', 'h.38.mlp.c_fc.bias', 'h.38.mlp.c_proj.weight', 'h.38.mlp.c_proj.bias', 'h.39.ln_1.weight', 'h.39.ln_1.bias', 'h.39.attn.bias', 'h.39.attn.masked_bias', 'h.39.attn.c_attn.weight', 'h.39.attn.c_attn.bias', 'h.39.attn.c_proj.weight', 'h.39.attn.c_proj.bias', 'h.39.ln_2.weight', 'h.39.ln_2.bias', 'h.39.mlp.c_fc.weight', 'h.39.mlp.c_fc.bias', 'h.39.mlp.c_proj.weight', 'h.39.mlp.c_proj.bias', 'h.40.ln_1.weight', 'h.40.ln_1.bias', 'h.40.attn.bias', 'h.40.attn.masked_bias', 'h.40.attn.c_attn.weight', 'h.40.attn.c_attn.bias', 'h.40.attn.c_proj.weight', 'h.40.attn.c_proj.bias', 'h.40.ln_2.weight', 'h.40.ln_2.bias', 'h.40.mlp.c_fc.weight', 'h.40.mlp.c_fc.bias', 'h.40.mlp.c_proj.weight', 'h.40.mlp.c_proj.bias', 'h.41.ln_1.weight', 'h.41.ln_1.bias', 'h.41.attn.bias', 'h.41.attn.masked_bias', 'h.41.attn.c_attn.weight', 'h.41.attn.c_attn.bias', 'h.41.attn.c_proj.weight', 'h.41.attn.c_proj.bias', 'h.41.ln_2.weight', 'h.41.ln_2.bias', 'h.41.mlp.c_fc.weight', 'h.41.mlp.c_fc.bias', 'h.41.mlp.c_proj.weight', 'h.41.mlp.c_proj.bias', 'h.42.ln_1.weight', 'h.42.ln_1.bias', 'h.42.attn.bias', 'h.42.attn.masked_bias', 'h.42.attn.c_attn.weight', 'h.42.attn.c_attn.bias', 'h.42.attn.c_proj.weight', 'h.42.attn.c_proj.bias', 'h.42.ln_2.weight', 'h.42.ln_2.bias', 'h.42.mlp.c_fc.weight', 'h.42.mlp.c_fc.bias', 'h.42.mlp.c_proj.weight', 'h.42.mlp.c_proj.bias', 'h.43.ln_1.weight', 'h.43.ln_1.bias', 'h.43.attn.bias', 'h.43.attn.masked_bias', 'h.43.attn.c_attn.weight', 'h.43.attn.c_attn.bias', 'h.43.attn.c_proj.weight', 'h.43.attn.c_proj.bias', 'h.43.ln_2.weight', 'h.43.ln_2.bias', 'h.43.mlp.c_fc.weight', 'h.43.mlp.c_fc.bias', 'h.43.mlp.c_proj.weight', 'h.43.mlp.c_proj.bias', 'h.44.ln_1.weight', 'h.44.ln_1.bias', 'h.44.attn.bias', 'h.44.attn.masked_bias', 'h.44.attn.c_attn.weight', 'h.44.attn.c_attn.bias', 'h.44.attn.c_proj.weight', 'h.44.attn.c_proj.bias', 'h.44.ln_2.weight', 'h.44.ln_2.bias', 'h.44.mlp.c_fc.weight', 'h.44.mlp.c_fc.bias', 'h.44.mlp.c_proj.weight', 'h.44.mlp.c_proj.bias', 'h.45.ln_1.weight', 'h.45.ln_1.bias', 'h.45.attn.bias', 'h.45.attn.masked_bias', 'h.45.attn.c_attn.weight', 'h.45.attn.c_attn.bias', 'h.45.attn.c_proj.weight', 'h.45.attn.c_proj.bias', 'h.45.ln_2.weight', 'h.45.ln_2.bias', 'h.45.mlp.c_fc.weight', 'h.45.mlp.c_fc.bias', 'h.45.mlp.c_proj.weight', 'h.45.mlp.c_proj.bias', 'h.46.ln_1.weight', 'h.46.ln_1.bias', 'h.46.attn.bias', 'h.46.attn.masked_bias', 'h.46.attn.c_attn.weight', 'h.46.attn.c_attn.bias', 'h.46.attn.c_proj.weight', 'h.46.attn.c_proj.bias', 'h.46.ln_2.weight', 'h.46.ln_2.bias', 'h.46.mlp.c_fc.weight', 'h.46.mlp.c_fc.bias', 'h.46.mlp.c_proj.weight', 'h.46.mlp.c_proj.bias', 'h.47.ln_1.weight', 'h.47.ln_1.bias', 'h.47.attn.bias', 'h.47.attn.masked_bias', 'h.47.attn.c_attn.weight', 'h.47.attn.c_attn.bias', 'h.47.attn.c_proj.weight', 'h.47.attn.c_proj.bias', 'h.47.ln_2.weight', 'h.47.ln_2.bias', 'h.47.mlp.c_fc.weight', 'h.47.mlp.c_fc.bias', 'h.47.mlp.c_proj.weight', 'h.47.mlp.c_proj.bias']
- This IS expected if you are initializing GPT2LMHeadModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing GPT2LMHeadModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of GPT2LMHeadModel were not initialized from the model checkpoint at models/mega-clue-tok/ and are newly initialized: ['ln_f.weight', 'ln_f.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Comment by ghosthamlet** [comment]
初始化和加载模型的部分代码可以贴上来看一下吗？

**Comment by Jasonjk3** [comment]
代码基本参考 https://github.com/yangjianxin1/GPT2-chitchat 这个项目的generate.py
参数部分:
parser = argparse.ArgumentParser()
    parser.add_argument('--device', default='0', type=str, required=False, help='生成设备')
    parser.add_argument('--temperature', default=1, type=float, required=False, help='生成的temperature')
    parser.add_argument('--topk', default=15, type=int, required=False, help='最高k选1')
    parser.add_argument('--topp', default=12, type=float, required=False, help='最高积累概率')
    parser.add_argument('--model_config', default='models/mega-clue-tok/config.json', type=str, required=False,
                        help='模型参数')
    parser.add_argument('--log_path', default='data/interacting.log', type=str, required=False, help='interact日志存放位置')
    parser.add_argument('--voca_path', default='models/mega-clue-tok/vocab.txt', type=str, required=False, help='选择词库')
    parser.add_argument('--dialogue_model_path', default='models/mega-clue-tok/', type=str, required=False, help='对话模型路径')
    parser.add_argument('--save_samples_path', default="sample/", type=str, required=False, help="保存聊天记录的文件路径")
    parser.add_argument('--repetition_penalty', default=2.2, type=float, required=False,
                        help="重复惩罚参数，若生成的对话重复性较高，可适当提高该参数")
    parser.add_argument('--seed', type=int, default=None, help='设置种子用于生成随机数，以使得训练的结果是确定的')
    parser.add_argument('--max_len', type=int, default=50, help='每个utterance的最大长度,超过指定长度则进行截断')
    parser.add_argument('--max_history_len', type=int, default=5, help="dialogue history的最大长度")
    parser.add_argument('--no_cuda',default=True, action='store_true', help='不使用GPU进行预测')


加载部分:
from transformers.modeling_gpt2 import GPT2Config, GPT2LMHeadModel
from transformers import BertTokenizer
tokenizer = BertTokenizer(vocab_file=args.voca_path)
model = GPT2LMHeadModel.from_pretrained(args.dialogue_model_path)
是因为ml和huggingface封装的gpt2模型结构不一致吗?

**Comment by ghosthamlet** [comment]
是的，huggingface的GPT2LMHeadModel和本库的不一样，你需要从本库调用修改后的GPT2LMHeadModel：
from gpt2_ml_torch.modeling_gpt2 import GPT2LMHeadModel

**Comment by Jasonjk3** [comment]
好的，感谢

**Comment by ghosthamlet** [comment]
不客气，微调有问题可以开新issue。

**Comment by Jasonjk3** [comment]
发现问题了，是我的改了模型参数测试，忘记调回来了，结构还是和huggingface的一样的
