### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by feb-cloud** [ghosthamlet/gpt2-ml-torch#15]
您好，请问下，有没有直接PyTorch训练模型的教程呢？换句话说就是完整的PyTorch版本，因为用了您的模型生成效果质量很高，想请教一下有没有你这个版本方法的训练教程，期待您的回复，谢谢。

**Comment by ghosthamlet** [comment]
谢谢关注，您如果对pytorch不太熟悉，官方的教程很不错，比如这个：https://pytorch.org/tutorials/beginner/transformer_tutorial.html ，
transformers类库的训练和微调方法可以参考：#8, 微调参数参考讨论：#13，本库内的微调示例：https://github.com/ghosthamlet/gpt2-ml-torch/blob/master/finetune_lm.py 是用来做文本生成的，和从头训练的数据结构和方法很相似，如果你想从头训练，也可以参考这个示例。

**Comment by feb-cloud** [comment]
> 谢谢关注，您如果对pytorch不太熟悉，官方的教程很不错，比如这个：https://pytorch.org/tutorials/beginner/transformer_tutorial.html ，
> transformers类库的训练和微调方法可以参考：#8, 微调参数参考讨论：#13，本库内的微调示例：https://github.com/ghosthamlet/gpt2-ml-torch/blob/master/finetune_lm.py 是用来做文本生成的，和从头训练的数据结构和方法很相似，如果你想从头训练，也可以参考这个示例。

收到，非常感谢您的回复。

**Comment by ghosthamlet** [comment]
不客气
