### ISSUE TITLE
模型问题请教

### ISSUE THREAD

**Issue by feb-cloud** [ghosthamlet/gpt2-ml-torch#16]
作者您好，我把torch模型拿到gpt2-chinese这个项目中使用，发现生成的文章都是乱码的，不清楚哪里出了问题，希望能够得到您的指点，多谢！期待您的回复。

**Comment by ghosthamlet** [comment]
本库的gpt2模型结构和通用的不太一样，你需要从本库import修改后的模型：
`from gpt2_ml_torch.modeling_gpt2 import GPT2LMHeadModel`
输入输出和通用gpt2是兼容的，用法参考：https://github.com/ghosthamlet/gpt2-ml-torch/blob/master/gpt2_ml_torch/generate.py

**Comment by Tao-Ya** [comment]
好的，非常感谢您的回复，辛苦了。

**Comment by feb-cloud** [comment]
> 本库的gpt2模型结构和通用的不太一样，你需要从本库import修改后的模型：
> `from gpt2_ml_torch.modeling_gpt2 import GPT2LMHeadModel`
> 输入输出和通用gpt2是兼容的，用法参考：https://github.com/ghosthamlet/gpt2-ml-torch/blob/master/gpt2_ml_torch/generate.py

非常感谢您的回复，辛苦啦。

**Comment by ghosthamlet** [comment]
不客气
