### ISSUE TITLE
方便给一个google drive的下载链接么？

### ISSUE THREAD

**Issue by henryxiao1997** [ghosthamlet/gpt2-ml-torch#17]
如题，谢谢！~

**Comment by ghosthamlet** [comment]
不好意思啊，我没有google帐号，你可以从gpt2-ml代码库提供的google drive地址：https://github.com/imcaspar/gpt2-ml#pretrained-model 下载Tensorflow版本，然后用本库代码把它转换成Pytorch版本。

**Comment by henryxiao1997** [comment]
好的，尝试用过代码库中的脚本，不过在cuda 9.x的系统上会出现 core dump。我已经从百度网盘上下载到了。谢谢！~

**Comment by ghosthamlet** [comment]
不客气。cuda 9.x有可能不兼容，我只测试过cuda 10.2，但转换模型不需要用到GPU，所以可能是和其他环境配置不兼容。
