### ISSUE TITLE
模型7z压缩文件损坏

### ISSUE THREAD

**Issue by Coldog2333** [ghosthamlet/gpt2-ml-torch#2]
您好，我试着下载了您转换好的模型文件。
在解压时候提示压缩文件损坏，请问您知道这要怎么解决吗？

**Comment by ghosthamlet** [comment]
模型文件分了好几片，可能是那一片上传或下载不完整，如果你已经下载过原gpt2-ml项目的tensorflow版本模型，可以用这个代码库试着自己转换，那也很容易，或者等我周末把未分片模型重新上传一次。

**Comment by ghosthamlet** [comment]
另外，你有没有选中模型的所有分片再解压？如果只选中其中一片有可能会报错。

**Comment by miven** [comment]
我这里解压也是失败 选中全部解压失败

**Comment by ghosthamlet** [comment]
已重新上传模型，代码也有部分修改，请同时更新代码，transformers类库也需要更新，模型下载查看：https://github.com/ghosthamlet/gpt2-ml-torch#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD

**Comment by Coldog2333** [comment]
十分感谢!
