### ISSUE TITLE
微调时出现JSONDecoeError

### ISSUE THREAD

**Issue by NLPIG** [ghosthamlet/gpt2-ml-torch#21]
Traceback (most recent call last):
File"finetune _1m. py, line 543, in <module>
1og_configsO
File "finetune_. py", line 539, in 1og_configs
file"c:\Users\Administrator\ AppData\loca\Programs\Python\ Python336\ib\json\init_.py",line354, in loads
return default decoder. decode(s)
Filec
ator\AppData \Local\Programs\Python\Python361ib\json\decoder. py", line 339, in decode
d self. raw decode(s, idx=w(s, 0). endO)
File"C: \Users
nistrator \AppData \Local\Programs\Python\(Python36\1ib\json\decoder. py", line 355, in raw_decode
obj, end self. scan once(s, idx)
json, decoder. JSONDecodeError: Expecting property name enclosed in double quotes line 2 column 7 (char 8)

**Comment by NLPIG** [comment]
另外，已经通过pip的方式下载好deepspeed，执行pip list 也有deepspeed，但是在CMD里执行deepspeed会报错，显示不是内部命令这个错误。
非常期待您的回复，非常感谢。

**Comment by ghosthamlet** [comment]
不好意思，你的第一个问题是调试用的configs/small.json的格式有问题，我之前传的json文件不对，已经改正了，你更新一下代码即可。
deepspeed报错的问题应该是需要设置环境变量，我用的是Linux，不太清楚Win的deepspeed执行文件目录是什么，你找一下它的执行文件的目录，再加到环境变量PATH中就行了。

**Comment by NLPIG** [comment]
> 不好意思，你的第一个问题是调试用的configs/small.json的格式有问题，我之前传的json文件不对，已经改正了，你更新一下代码即可。
> deepspeed报错的问题应该是需要设置环境变量，我用的是Linux，不太清楚Win的deepspeed执行文件目录是什么，你找一下它的执行文件的目录，再加到环境变量PATH中就行了。

谢谢！

**Comment by NLPIG** [comment]
> 不好意思，你的第一个问题是调试用的configs/small.json的格式有问题，我之前传的json文件不对，已经改正了，你更新一下代码即可。
> deepspeed报错的问题应该是需要设置环境变量，我用的是Linux，不太清楚Win的deepspeed执行文件目录是什么，你找一下它的执行文件的目录，再加到环境变量PATH中就行了。

不好意思还得继续麻烦您帮忙解答另一问题：
from gpt2_ml_torch.config import MODEL_PATH
ModuleNotFoundError: No module named 'gpt2_ml_torch'
这个问题是通过文件夹 'gpt2_ml_torch'导入里面的config文件，这个时候python识别不了 'gpt2_ml_torch'文件夹吗？请问需要怎么做呢？

**Comment by ghosthamlet** [comment]
@NLPIG 你执行代码的目录下面有gpt2_ml_torch这个子文件夹吗？如果有的话应该不会报这个错。
因为gpt2_ml_torch这个库只有源码没有安装，所以当前工作文件夹最好和源代码中README.md在同一个文件夹。

**Comment by NLPIG** [comment]
> @NLPIG 你执行代码的目录下面有gpt2_ml_torch这个子文件夹吗？如果有的话应该不会报这个错。
> 因为gpt2_ml_torch这个库只有源码没有安装，所以当前工作文件夹最好和源代码中README.md在同一个文件夹。

有的，我是直接zipdownload您的代码库

**Comment by NLPIG** [comment]
> > @NLPIG 你执行代码的目录下面有gpt2_ml_torch这个子文件夹吗？如果有的话应该不会报这个错。
> > 因为gpt2_ml_torch这个库只有源码没有安装，所以当前工作文件夹最好和源代码中README.md在同一个文件夹。
> 
> 有的，我是直接zipdownload您的代码库

【已解决】import OS，添加path路径即可，谢谢
