### ISSUE TITLE
请问怎么把训练好的pytorch模型转换回tensorflow模型呢，有哪些需要注意的地方吗？

### ISSUE THREAD

**Issue by NLPIG** [ghosthamlet/gpt2-ml-torch#23]

**Comment by ghosthamlet** [comment]
@NLPIG 不好意思，刚看到你的问题。这个gpt2模型和标准的gpt2不太一样，是另一篇论文修改gpt2得到的GROVER模型，所以无法用transformers类库内置的转换工具转换，除非你在github能找到pytorch GROVER转tensorflow模型的代码，否则只能自己写这个代码了。本类库中的modeling_gpt2.py文件中第一个load_tf_weights_in_gpt2函数是tensorflow转pytorch的核心函数，把这个函数中模型权重的操作反转一下应该就能转换了。不过你需要对pytorch、tensorflow和transformers三个类库都比较熟悉才可能做到。
另外，你做tensorflow模型转换是不是为了deploy？其实pytorch现在也有很好的各种deploy方案，可能比模型转换更容易运用。

**Comment by NLPIG** [comment]
> @NLPIG 不好意思，刚看到你的问题。这个gpt2模型和标准的gpt2不太一样，是另一篇论文修改gpt2得到的GROVER模型，所以无法用transformers类库内置的转换工具转换，除非你在github能找到pytorch GROVER转tensorflow模型的代码，否则只能自己写这个代码了。本类库中的modeling_gpt2.py文件中第一个load_tf_weights_in_gpt2函数是tensorflow转pytorch的核心函数，把这个函数中模型权重的操作反转一下应该就能转换了。不过你需要对pytorch、tensorflow和transformers三个类库都比较熟悉才可能做到。
> 另外，你做tensorflow模型转换是不是为了deploy？其实pytorch现在也有很好的各种deploy方案，可能比模型转换更容易运用。

大佬您好，果然是因为标准问题无法直接转换，如果这样的话我确实没法做到。我是为了部署，然后之前提了个issue是关于交互式输入的（就是只运行一次模型加载，然后你只需要每次键入新信息给它，像GPT2ML的colab demo那样），然后根据您的提示，我做了模型调用，奇怪的是它依然是每次都重新加载模型，我也不好意思继续追问，所以就想转换回TF版本直接copy那边的demo代码（不想只做伸手党，却又能力有限）。

**Comment by ghosthamlet** [comment]
@NLPIG 可能是你每次把加载和生成的代码都一起执行了，所以会重复加载。交换式生成代码中，以下是加载模型，只能运行一次：
```
from gpt2_ml_torch.config import MODEL_PATH

from gpt2_ml_torch.generate import build_model, build_output

model,  tokenizer, _ = build_model(MODEL_PATH)
```

以下是生成代码，每次生成时调用：
```
print(build_output(model, tokenizer,
           prompt='中国人是', n_seq=1, max_len=100, no_gpu=False))
```

**Comment by NLPIG** [comment]
> @NLPIG 可能是你每次把加载和生成的代码都一起执行了，所以会重复加载。交换式生成代码中，以下是加载模型，只能运行一次：
> 
> ```
> from gpt2_ml_torch.config import MODEL_PATH
> 
> from gpt2_ml_torch.generate import build_model, build_output
> 
> model,  tokenizer, _ = build_model(MODEL_PATH)
> ```
> 
> 以下是生成代码，每次生成时调用：
> 
> ```
> print(build_output(model, tokenizer,
>            prompt='中国人是', n_seq=1, max_len=100, no_gpu=False))
> ```

对，我是加载和生成一起执行了，再次表示感谢！

**Comment by ghosthamlet** [comment]
不客气，没问题的话我就关闭这个issue了，其他问题可以再开新的。
