### ISSUE TITLE
关于修改--log_name之后模型无法训练，和语料大小对训练时长没有影响两个问题

### ISSUE THREAD

**Issue by NLPIG** [ghosthamlet/gpt2-ml-torch#24]
再次期望您的指导！谢谢！

**Comment by ghosthamlet** [comment]
@NLPIG 第一个log_name的问题很奇怪，修改不应该造成OUT OF MEMORY问题，可以把全部训练的参数贴上来看看吗？
第二个问题【502/522827】522827没错是数据集的实例数，你可以看finetune_lm.py这个文件中的log相关代码就明白了，finetune_lm.py这个文件中代码其实不复杂，如果你用的比较多的话，我建议花点时间阅读一下，对调试很有好处。你提到的test_train.txt的大小变了，但【502/522827】没变，应该是训练参数--train_data地址设置有问题，没有指到正确的test_train.txt文件。
另外，微调前和微调后模型参数数量是不变的，都是15亿，微调用了16位训练，所以文件大小会缩小一半左右。

**Comment by ghosthamlet** [comment]
@NLPIG 对了，我忘记finetune_lm.py微调时会自动缓存预处理后的数据集，缓存文件在当前caches目录下，文件名格式：log_name-train.json和log_name-valid.json，如果log_name是ABC_large_stage2，缓存文件名就是：ABC_large_stage2-train.json和ABC_large_stage2-valid.json，修改log_name出现OUT OF MEMORY，可能新log_name之前有过缓存，而且这个缓存的seq_len比较大，你可以加个参数--no_cache禁止用缓存，不过这样每次都会重新预处理数据比较慢，最好是换一个log_name或者手工清除caches目录下文件。
第二个问题应该也是缓存的问题，按前面的方法处理即可。

**Comment by NLPIG** [comment]
> @NLPIG 对了，我忘记finetune_lm.py微调时会自动缓存预处理后的数据集，缓存文件在当前caches目录下，文件名格式：log_name-train.json和log_name-valid.json，如果log_name是ABC_large_stage2，缓存文件名就是：ABC_large_stage2-train.json和ABC_large_stage2-valid.json，修改log_name出现OUT OF MEMORY，可能新log_name之前有过缓存，而且这个缓存的seq_len比较大，你可以加个参数--no_cache禁止用缓存，不过这样每次都会重新预处理数据比较慢，最好是换一个log_name或者手工清除caches目录下文件。
> 第二个问题应该也是缓存的问题，按前面的方法处理即可。

对，果然是缓存的问题，代码我仔细研究过了，不难（结合百度谷歌），到目前为止基本没问题了。修改log_name造成OUT OF MEMORY是因为sep长度和bs太大，改小就好了，不过之前同样的sep_len和bs却能训练，很奇怪，应该是val文本比较大的问题（因为默认的text_val.txt非常小，我添加自己的数据后大小达到50Mb，其他都不变，所以应该是这个val的问题了）。
最后一个问题，text_val.txt这个验证数据文件的大小对生成质量影响大吗，我的train loss一直比val loss高（0.01左右）。
text_val.txt的数据是从text_train.txt里面截取的。

**Comment by ghosthamlet** [comment]
train loss和val loss相差0.01是非常小了，对生成质量没有影响。

**Comment by NLPIG** [comment]
> train loss和val loss相差0.01是非常小了，对生成质量没有影响。

请问，max_len有办法突破1024限制吗，我尝试在generate中修改代码，并没有成功。

**Comment by ghosthamlet** [comment]
因为训练的seq_len最大只有1024，所以生成的上下文最大也只能是1024，但可以在第一次生成1024字后，按如下方法连续生成不限长度内容：
1. 用上一次生成的末尾1023字作为输入，生成下一个字
2. 重复步骤1即可

**Comment by NLPIG** [comment]
> 因为训练的seq_len最大只有1024，所以生成的上下文最大也只能是1024，但可以在第一次生成1024字后，按如下方法连续生成不限长度内容：
> 
> 1. 用上一次生成的末尾1023字作为输入，生成下一个字
> 2. 重复步骤1即可

哈哈，这个妙！
