### ISSUE TITLE
请问为什么 15G 语料模型的对话生成质量反而比 30G 的好？

### ISSUE THREAD

**Issue by realLINorth** [ghosthamlet/gpt2-ml-torch#26]

**Comment by ghosthamlet** [comment]
@realLINorth 不好意思，刚看到你的问题。
这和数据及模型训练各方面有关，影响因素比较多：
1. 有可能15G语料中对话和小说内容的比率较高，而30G中比率较低；
2. 此模型不算特别大，15G数据可以拟合的更好，30G则可能欠拟合；
3. 30G的模型虽然训练时间比15G更长，但也可能仍然不足。

另外对话质量的问题我只是手工生成几次做的对比，没有做专门的评测，所以覆盖面不广，不一定有代表性。

**Comment by realLINorth** [comment]
感谢解答！
