### ISSUE TITLE
请问是否无损转化，即和huggingface库的代码中参数对的上吗？

### ISSUE THREAD

**Issue by lemon234071** [ghosthamlet/gpt2-ml-torch#5]

**Comment by ghosthamlet** [comment]
是无损转化，和huggingface库的参数一致，只有modeling_gpt2.py中加_USE_GROVER条件内的代码是新增的。

**Comment by lemon234071** [comment]
> 是无损转化，和huggingface库的参数一致，只有modeling_gpt2.py中加_USE_GROVER条件内的代码是新增的。

十分感谢

**Comment by ghosthamlet** [comment]
不客气
