### ISSUE TITLE
模型無法下載

### ISSUE THREAD

**Issue by Sheng-Ru** [ghosthamlet/gpt2-ml-torch#7]
你好 現在的百度網盤好像失效 沒辦法下載模型了

**Comment by ghosthamlet** [comment]
有没有什么提示？我试了下可以下载。

**Comment by Sheng-Ru** [comment]
我這邊按百度網盤的連結 會顯示頁面不存在

**Comment by ghosthamlet** [comment]
我重新分享一下，你再试试：链接: https://pan.baidu.com/s/17OW_dRfjT6W6pmdBb0Fmig 提取码: q7nn 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Sheng-Ru** [comment]
情況一樣，我在想會不會是因為我這邊是台灣IP，應該被擋了

**Comment by ghosthamlet** [comment]
有可能，其他百度网盘地址你能打开吗？或者再试试用VPN看能不能行。

**Comment by ghosthamlet** [comment]
我可以把你加为网盘好友，看直接共享行不行

**Comment by Sheng-Ru** [comment]
我現在可以了  謝謝你

**Comment by ghosthamlet** [comment]
不客气
